// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMQmDhwP7lOrg-s6Ul4YEb9ACXg1i87UY',
    appId: '1:572741789169:web:c4cd1813b2542c93e99050',
    messagingSenderId: '572741789169',
    projectId: 'budgetbuddy-b95c6',
    authDomain: 'budgetbuddy-b95c6.firebaseapp.com',
    storageBucket: 'budgetbuddy-b95c6.firebasestorage.app',
    measurementId: 'G-T1G8YCXVN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYMrHkjN8pMJQPpV-XVtUhWX5CMd7ekVw',
    appId: '1:572741789169:android:706d7194558c2168e99050',
    messagingSenderId: '572741789169',
    projectId: 'budgetbuddy-b95c6',
    storageBucket: 'budgetbuddy-b95c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnaiqad-pK8dz613-InCceERcYJrxTKwA',
    appId: '1:572741789169:ios:2282ed0b447625aae99050',
    messagingSenderId: '572741789169',
    projectId: 'budgetbuddy-b95c6',
    storageBucket: 'budgetbuddy-b95c6.firebasestorage.app',
    iosBundleId: 'com.example.budgetBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnaiqad-pK8dz613-InCceERcYJrxTKwA',
    appId: '1:572741789169:ios:2282ed0b447625aae99050',
    messagingSenderId: '572741789169',
    projectId: 'budgetbuddy-b95c6',
    storageBucket: 'budgetbuddy-b95c6.firebasestorage.app',
    iosBundleId: 'com.example.budgetBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMQmDhwP7lOrg-s6Ul4YEb9ACXg1i87UY',
    appId: '1:572741789169:web:4e8f031c56a4f476e99050',
    messagingSenderId: '572741789169',
    projectId: 'budgetbuddy-b95c6',
    authDomain: 'budgetbuddy-b95c6.firebaseapp.com',
    storageBucket: 'budgetbuddy-b95c6.firebasestorage.app',
    measurementId: 'G-54YECS3TLC',
  );
}
